project:
  type: website
  output-dir: docs

website:
  # basic metadata
  title: "Our Italy in Data"
  
  # stuff
  cookie-consent:
    type: express
    style: interstitial
  reader-mode: true
  back-to-top-navigation: true
  bread-crumbs: false
  
  # navigation bar
  navbar:
    tools:
      - icon: github
        href: "https://github.com/SimoneBrazzi/OIID"
    search: true
    left:
      - text: "About"
        href: about.qmd

  sidebar:
    - id: browse_by_topic
      title: "Browse by topic"
      collapse-level: 4
      contents:
        - section: Population and Demographic Change
          contents:
            - topics/Population and Demographic Change/01_population_growth.qmd
            - topics/Population and Demographic Change/02_age_structure.qmd
        - section: Health
          contents:
            - topics/Health/01_heath_test.qmd
        - section: Poverty and Economic Development
          contents:
            - topics/Poverty and Economic Development/01_economic_growth.qmd
        - section: TEST
          contents:
            - topics/TEST/test.qmd
  
format:
  html:
    theme:
      light: [flatly, theme_light_custom.scss] 
      dark: [darkly, theme_dark_custom.scss]
    code-link: TRUE
    code-fold: show
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual
