project:
  type: website
  output-dir: docs

website:
  cookie-consent:
    type: express
    style: interstitial
  title: "Our Italy in Data"
  # favicon:
  site-url: "https://simonebrazzi.github.io/OIID/"
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    search: true
    left:
      - sidebar:topic # hamburgher menu
      # - sidebar:latest
      # - sidebar:resources # drop down
      - text: "About"
        href: about.qmd
  
  sidebar:
    - id: topic
      title: "Browse by topic"
      style: "floating"
      contents: auto
  
format:
  html:
    theme:
      dark: [darkly, theme_dark_custom.scss]
      light: [flatly, theme_light_custom.scss] 
    code-link: TRUE
    code-fold: show
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual

