project:
  type: website
  output-dir: docs

website:
  title: "OIID"
  # favicon:
  site-url: "https://simonebrazzi.github.io/OIID/"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Browse by topic" # hamburgher menu
      - text: "Latest"
      - text: "Resources" # drop down
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      dark: [darkly, theme_dark_custom.scss]
      light: [flatly, theme_light_custom.scss] 
    code-link: TRUE
    code-fold: show
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual

