project:
  type: website
  output-dir: docs

website:
  # basic metadata
  title: "Our Italy in Data"
  open-graph: true
  
  # stuff
  cookie-consent:
    type: express
    style: interstitial
  reader-mode: true
  back-to-top-navigation: true
  bread-crumbs: false
  
  # navigation bar
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:topics

  sidebar:
    - id: topics
      title: "Topics"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics


# format
format:
  html:
    theme:
      light: [flatly, theme_light_custom.scss] 
      dark: [darkly, theme_dark_custom.scss]
    code-link: TRUE
    code-fold: show
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual
