project:
  type: website
  output-dir: docs

website:
  # basic metadata
  title: "Our Italy in Data"
  open-graph: true
  
  # stuff
  cookie-consent:
    type: express
    style: interstitial
  reader-mode: true
  back-to-top-navigation: true
  bread-crumbs: false
  
  # navigation bar
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/SimoneBrazzi/OIID/tree/main
          - text: Report a Bug
            href: https://github.com/SimoneBrazzi/OIID/issues

    left:
      - text: "Home"
        href: index.qmd
      - sidebar:topics

  sidebar:
    - id: topics
      title: "Topics"
      style: "docked"
      background: light
      collapse-level: 2
      contents: topics

# execute
execute:
  eval: true
  freeze: auto
  cache: true
  echo: true
  message: false
  warning: false

# format
format:
  html:
    theme:
      light: [flatly, theme_light_custom.scss] 
      dark: [darkly, theme_dark_custom.scss]
    code-link: TRUE
    code-fold: true
    code-line-numbers: TRUE
    code-copy: TRUE
    highlight-style: monokai
    toc: true

editor: visual
