project:
  type: website
  output-dir: docs

website:
  title: "OIID"
  # favicon:
  site-url: "https://simonebrazzi.github.io/OIID/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: [darkly, theme_dark_custom.scss]
      light: [flatly, theme_light_custom.scss] 
    css: styles.css
    toc: true

editor: visual

